import { Internship } from '../types';

export const internships: Internship[] = [
  { id: 1, title: 'Digital Literacy Trainer Assistant', company: 'Pratham Foundation', location: 'Rural Rajasthan', description: 'Assist in conducting digital literacy workshops for local community members. Help create simple training modules and provide hands-on support.', requiredSkills: ['MS Office', 'Communication', 'Patience'], sector: 'Education' },
  { id: 2, title: 'Organic Farming Field Assistant', company: 'Navdanya', location: 'Dehradun, Uttarakhand', description: 'Learn and assist with sustainable agriculture practices, including seed saving, composting, and pest management on an organic farm.', requiredSkills: ['Hard work', 'Interest in Agriculture'], sector: 'Agriculture' },
  { id: 3, title: 'Community Health Worker Support', company: 'ASHA Program (Govt.)', location: 'Tribal District, Jharkhand', description: 'Support local ASHA workers in community outreach, health surveys, and awareness campaigns for maternal and child health.', requiredSkills: ['Local Language', 'Interpersonal Skills'], sector: 'Healthcare' },
  { id: 4, title: 'Panchayat Documentation Assistant', company: 'District Rural Development Agency', location: 'Bastar, Chhattisgarh', description: 'Assist the Panchayat office in digitizing records, documenting meetings, and preparing reports for government schemes.', requiredSkills: ['Basic Computer Skills', 'Data Entry', 'Hindi Typing'], sector: 'Government' },
  { id: 5, title: 'Micro-Finance Field Officer Trainee', company: 'Bandhan Bank', location: 'Rural West Bengal', description: 'Work with field officers to understand micro-finance operations, support self-help groups (SHGs), and assist with loan documentation.', requiredSkills: ['Communication', 'Basic Math'], sector: 'Finance' },
  { id: 6, title: 'Social Media Handler for NGO', company: 'CRY - Child Rights and You', location: 'Delhi', description: 'Manage and create content for the NGO\'s social media pages to raise awareness about child rights issues.', requiredSkills: ['Social Media', 'Content Writing', 'Canva'], sector: 'Social Work' },
  { id: 7, title: 'Data Entry Operator', company: 'National Informatics Centre', location: 'Bhopal, Madhya Pradesh', description: 'Perform data entry and verification tasks for various e-governance projects.', requiredSkills: ['Typing Speed', 'MS Excel', 'Attention to Detail'], sector: 'IT' },
  { id: 8, title: 'E-commerce Operations Intern', company: 'Flipkart', location: 'Bangalore, Karnataka', description: 'Assist with catalog management, order processing, and seller support for a major e-commerce platform.', requiredSkills: ['MS Excel', 'Communication'], sector: 'E-commerce' },
  { id: 9, title: 'Hospital Front Desk Assistant', company: 'Apollo Hospitals', location: 'Chennai, Tamil Nadu', description: 'Assist with patient registration, appointment scheduling, and handling inquiries at the hospital front desk.', requiredSkills: ['Communication', 'Politeness', 'Computer Skills'], sector: 'Healthcare' },
  { id: 10, title: 'Content Writing Intern (Hindi)', company: 'Gaon Connection', location: 'Lucknow, Uttar Pradesh', description: 'Write and translate articles on rural issues, agriculture, and community stories for a rural media platform.', requiredSkills: ['Hindi Writing', 'Storytelling'], sector: 'Media' },
  { id: 11, title: 'Rural School Teaching Assistant', company: 'Teach for India', location: 'Pune, Maharashtra', description: 'Support teachers in a low-income school with classroom management, conducting activities, and providing one-on-one help to students.', requiredSkills: ['Patience', 'Love for children', 'Communication'], sector: 'Education' },
  { id: 12, title: 'Water Conservation Project Intern', company: 'Paani Foundation', location: 'Rural Maharashtra', description: 'Participate in watershed management projects, conduct community mobilization activities, and collect field data.', requiredSkills: ['Field Work', 'Communication'], sector: 'Environment' },
  { id: 13, title: 'IT Helpdesk Trainee', company: 'Wipro', location: 'Hyderabad, Telangana', description: 'Provide basic technical support to internal employees, troubleshoot hardware and software issues, and escalate problems as needed.', requiredSkills: ['Problem Solving', 'Computer Hardware basics'], sector: 'IT' },
  { id: 14, title: 'Handicraft Marketing Assistant', company: 'Fabindia', location: 'Jaipur, Rajasthan', description: 'Assist in cataloging new handicraft products, coordinating with artisans, and supporting the marketing team.', requiredSkills: ['MS Excel', 'Organization'], sector: 'Retail' },
  { id: 15, title: 'Library Management Intern', company: 'District Library', location: 'Patna, Bihar', description: 'Help with cataloging books, managing memberships, and organizing library events for children.', requiredSkills: ['Organization', 'Love for books'], sector: 'Education' },
  { id: 16, title: 'Renewable Energy Survey Intern', company: 'SELCO Foundation', location: 'Rural Karnataka', description: 'Conduct surveys in rural areas to assess the need and feasibility of solar energy solutions for homes and small businesses.', requiredSkills: ['Surveying', 'Data Collection', 'Kannada'], sector: 'Energy' },
  { id: 17, title: 'Customer Support Executive Trainee', company: 'Airtel', location: 'Gurgaon, Haryana', description: 'Learn to handle customer queries via phone and email, resolve basic issues, and provide information about products and services.', requiredSkills: ['Communication', 'Listening Skills'], sector: 'Telecommunication' },
  { id: 18, title: 'Digital Marketing Intern', company: 'A small IT startup', location: 'Indore, Madhya Pradesh', description: 'Assist with SEO, social media marketing, and email campaigns for the company\'s products.', requiredSkills: ['Social Media', 'Basic English Writing'], sector: 'IT' },
  { id: 19, title: 'Animal Shelter Volunteer Coordinator', company: 'People for Animals', location: 'Mumbai, Maharashtra', description: 'Help manage volunteers, coordinate animal care schedules, and assist with adoption drives.', requiredSkills: ['Love for animals', 'Organization'], sector: 'Social Work' },
  { id: 20, title: 'Tourism Promotion Intern', company: 'Odisha Tourism', location: 'Bhubaneswar, Odisha', description: 'Assist in creating promotional materials, handling social media, and providing information to tourists at information centers.', requiredSkills: ['Communication', 'Odia language', 'Social Media'], sector: 'Tourism' },
  { id: 21, title: 'Survey Data Analyst Intern', company: 'Nielsen', location: 'Kolkata, West Bengal', description: 'Clean and analyze survey data using Excel and other tools to generate basic reports.', requiredSkills: ['MS Excel', 'Analytical Skills'], sector: 'Market Research' },
  { id: 22, title: 'Forestry Field Intern', company: 'State Forest Department', location: 'Wayanad, Kerala', description: 'Assist forest rangers in wildlife monitoring, nursery management, and community awareness programs.', requiredSkills: ['Physical Fitness', 'Interest in nature'], sector: 'Environment' },
  { id: 23, title: 'Waste Management Project Assistant', company: 'Chintan Environmental Research', location: 'Delhi', description: 'Work with waste-picker communities on waste segregation projects and awareness campaigns.', requiredSkills: ['Field Work', 'Communication'], sector: 'Environment' },
  { id: 24, title: 'Telemedicine Center Operator', company: 'Primary Health Centre (Govt.)', location: 'Remote village, Arunachal Pradesh', description: 'Facilitate video consultations between patients and doctors, manage records, and operate telemedicine equipment.', requiredSkills: ['Basic Computer Skills', 'Communication'], sector: 'Healthcare' },
  { id: 25, title: 'Frontend Web Development Intern', company: 'Tech Mahindra Foundation', location: 'Noida, Uttar Pradesh', description: 'Learn and assist in creating simple web pages using HTML, CSS, and basic JavaScript for internal projects.', requiredSkills: ['HTML', 'CSS', 'Logical thinking'], sector: 'IT' },
  { id: 26, title: 'Supply Chain Operations Trainee', company: 'BigBasket', location: 'Pune, Maharashtra', description: 'Learn about warehouse operations, inventory management, and the process of order fulfillment.', requiredSkills: ['Attention to Detail', 'MS Excel'], sector: 'Logistics' },
  { id: 27, title: 'Nutrition Awareness Camp Assistant', company: 'Anganwadi Program (Govt.)', location: 'Koraput, Odisha', description: 'Support Anganwadi workers in organizing nutrition and health awareness camps for mothers and children.', requiredSkills: ['Local Language', 'Interpersonal Skills'], sector: 'Healthcare' },
  { id: 28, title: 'Right to Information (RTI) Filing Assistant', company: 'MKSS', location: 'Rural Rajasthan', description: 'Help community members understand and file RTI applications to get information from government departments.', requiredSkills: ['Reading and Writing', 'Attention to Detail'], sector: 'Social Work' },
  { id: 29, title: 'Event Management Support Intern', company: 'A local event company', location: 'Ahmedabad, Gujarat', description: 'Assist in planning and executing local events, coordinating with vendors, and managing on-ground activities.', requiredSkills: ['Communication', 'Organization', 'Hard work'], sector: 'Events' },
  { id: 30, title: 'Quality Control Intern (Garments)', company: 'Shahi Exports', location: 'Tiruppur, Tamil Nadu', description: 'Learn basic quality checking processes in a garment manufacturing unit, including fabric and stitching inspection.', requiredSkills: ['Attention to Detail', 'Observant'], sector: 'Manufacturing' },
  ...Array.from({ length: 170 }, (_, i) => i + 31).map(id => {
    const sectors = ['IT', 'Healthcare', 'Education', 'Agriculture', 'Government', 'Social Work', 'Finance', 'Retail', 'Environment', 'Manufacturing'];
    const locations = ['Rural Punjab', 'Shillong, Meghalaya', 'Visakhapatnam, Andhra Pradesh', 'Guwahati, Assam', 'Ranchi, Jharkhand', 'Chandigarh', 'Thiruvananthapuram, Kerala', 'Srinagar, Jammu & Kashmir', 'Gangtok, Sikkim', 'Agartala, Tripura'];
    const companies = ['Ministry of Tribal Affairs', 'Self Employed Women\'s Association (SEWA)', 'State Bank of India', 'Reliance Retail', 'The Energy and Resources Institute (TERI)', 'Tata Motors', 'Infosys Springboard', 'Narayana Health', 'Akshara Foundation', 'Digital Green'];
    const titles = ['Scheme Monitoring Intern', 'Community Mobilizer', 'Financial Literacy Trainer', 'Store Operations Assistant', 'Environmental Survey Assistant', 'Assembly Line Trainee', 'Software Testing Intern', 'Medical Records Assistant', 'Educational Content Creator', 'Agricultural Video Production Assistant'];
    const skills = [['Data Analysis', 'MS Excel'], ['Public Speaking', 'Local Language'], ['Presentation Skills', 'Finance Basics'], ['Customer Service', 'Inventory'], ['Data Collection', 'Communication'], ['Teamwork', 'Discipline'], ['Logical Thinking', 'Testing'], ['Organization', 'Typing'], ['Content Creation', 'Creativity'], ['Video Editing', 'Farming Knowledge']];
    
    const index = (id - 31) % 10;
    
    return {
      id,
      title: titles[index],
      company: companies[index],
      location: locations[index],
      description: `A hands-on internship to support the ${companies[index]} team in ${locations[index]} with tasks related to ${sectors[index].toLowerCase()}.`,
      requiredSkills: skills[index],
      sector: sectors[index]
    };
  })
];
